# используем язык
language: java
# версия jdk
jdk: openjdk11

# Отправлять уведомление на почту
notifications:
  email:
    recipients:
      - k-valentin-1989@yandex.ru
    on_success: always
    on_failure: always