# используем язык
language: java
# версия jdk
jdk: openjdk11



# Отправлять уведомление на почту
notifications:
  email:
    recipients:
      - k-valentin-1989@yandex.ru
    on_success: always
    on_failure: always

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - CODECOV_TOKEN="7da0b4cd-d1e4-4c80-9aaf-cc7d09dd882e"